### ISSUE TITLE
Tool bar is not displayed

### ISSUE THREAD

**Issue by jyagasaki** [splitbrain/dokuwiki-plugin-translation#72] opened 2015-05-26 10:47 UTC
Hi,

I installed the plugin of 2015/05/22 version.
As a result, toolbar is not displayed in the editing page except the default language.
Is this right behavior ?

Regards,
J.Yagasaki

**Comment by splitbrain** [comment] 2015-05-27 05:00
certainly not the right behavior. please check doku.wiki/faq:toolbar and report back with more details

**Comment by jyagasaki** [comment] 2015-05-27 08:56
Hi 

Thank you very much for your reply.

I will provide you the detailed information.

First, I checked "Problem with DokuWiki" of doku.wiki/faq:toolbar, so No.1-7 seems like no problem.
In the previous version of this plugin, toolbar was displayed.
On uninstalling current version, this issue does not appears.
In the JavaScript Error console of Firefox, an error is occurred as follows:
  SyntaxError: expected expression, got '<'1  js.php:1:0

Regards,
J.Yagasaki

**Comment by splitbrain** [comment] 2015-05-29 12:03
which languages have you configured? what are your other settings for the translation plugin?

can you disable the compress options and check if you still get an error and what it says?

**Comment by jyagasaki** [comment] 2015-06-01 02:24
Hi

I am sorry for the lack of explanation.

"ja" has been set in [lang] settings, and translation language is "en".

I have been disabled  the compress options, but still got errors as follows;
SyntaxError: expected expression, got '<'1  js.php:1:0
ReferenceError: DOKU_BASE is not defined  script-cmpr.js:1:5970

Best Regards,
J.Yagasaki

**Comment by foisys** [comment] 2015-06-03 20:20
Hi,

I can confirm this behaviour in my own dokuwiki install. The toolbars, either from dokuwiki builtin editor or ckgedit editor, do not appears after upgrade to latest version. All pages outside of the translation zone (for example, pages in the users namespace) are not affected; only pages that are under specific languages have this problem, in my case, en and fr namespaces. 

My Safari error console ends me this:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

I will revert to an older version in the mean time.

Best regards

Sylvain Foisy, Ph. D.
Project Manager Bioinformatics
Montreal Heart Institute
Montreal,Qc CANADA

**Comment by Kasara** [comment] 2015-06-15 13:29
The problem is:
/lib/exe/js.php?tseed=*****&lang=de 
If I set 3 letters (like "ger" or "eng") the scripts loads, but that is not the right solution, because the flags are not shown any longer and the correct language shortcut should be "de" and "en"

**Comment by Kasad** [comment] 2015-06-16 11:06
Found the solution: update your js.php to the current version:
https://raw.githubusercontent.com/splitbrain/dokuwiki/master/lib/exe/js.php
Now it works again :)

**Comment by Kasad** [comment] 2015-06-16 12:19
I found the option / reason:

if the option 
plugin»translation»translateui
is activated, the url 
/lib/exe/js.php?lang=****language**** 
results in an error

I disable the option for now, but I hope this finding helps the author to fix the bug :)

Sincerely

**Comment by LMS235** [comment] 2015-06-24 11:19
I have the same problem (see https://forum.dokuwiki.org/thread/12720 ) with 2015-05-22 (on 2014-09-29d "Hrun")

if translateui = 1, the sidebar (indexmenue) and the toolbar (here with codemirror plugin) dose not work
if translateui = 0, all is OK

**Comment by splitbrain** [comment] 2015-06-30 18:58
should be fixed with the fix for #74

**Closed by splitbrain** 2015-06-30 18:58 UTC
