### ISSUE TITLE
wrong path, NS gets doubled while using "translationns"

### ISSUE THREAD

**Issue by studmed** [splitbrain/dokuwiki-plugin-translation#285] opened 2023-05-22 18:33 UTC
Hello,
I tried this out with a clean DW.
When I usw "translationns" the path ends up being wrong because the NS I put in there gets put in front of the original path AND also in front of the language code:
NS:site becomes 

- NS:NS:site  for my default language
- NS:en:NS:site for the additional language

If I switch it off it works just fine for all namespaces, but I want it restricted to just one particular.

**Comment by splitbrain** [comment] 2023-05-23 08:20
duplicate of #61

**Closed by splitbrain** 2023-05-23 08:20 UTC
